plugins {
    id 'com.android.application'
}

android {
    namespace 'com.brainwatch'
    compileSdk 34

    defaultConfig {
        applicationId "com.brainwatch"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    signingConfigs {
        release {
            storeFile rootProject.file("brainwatch.keystore")
            storePassword "brainwatch123"
            keyAlias "brainwatch"
            keyPassword "brainwatch123"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
        debug {
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
}